package modelo.entidad;
// Generated 26/04/2015 09:48:39 AM by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private long idcliente;
     private String nombres;
     private String apellidos;
     private int dni;
     private String sexo;

    public Cliente() {
    }

    public Cliente(long idcliente, String nombres, String apellidos, int dni, String sexo) {
       this.idcliente = idcliente;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.dni = dni;
       this.sexo = sexo;
    }
   
    public long getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(long idcliente) {
        this.idcliente = idcliente;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


